# Generated by Django 6.0.3 on 2026-04-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_enrollment_certificate'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='certificate_id',
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='view_time',
            field=models.IntegerField(default=0),
        ),
    ]
