# Generated by Django 6.0.3 on 2026-04-12 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_certificate_certificate_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='duration',
            field=models.IntegerField(default=0, help_text='Duration in seconds'),
        ),
    ]
