# Generated by Django 6.0.3 on 2026-04-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_courses_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='video_url',
            field=models.URLField(help_text='Paste the YouTube video link here', unique=True),
        ),
    ]
