# Generated by Django 6.0.3 on 2026-04-12 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_courses_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='last_timestamp',
            field=models.IntegerField(default=0),
        ),
    ]
