# Generated by Django 6.0 on 2026-04-22 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_courses_is_legacy_module_lesson_lessonprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
